[package]
org = "ballerina"
name = "io"
version = "1.2.2"
authors = ["Ballerina"]
keywords = ["io", "json", "xml", "csv", "file"]
repository = "https://github.com/ballerina-platform/module-ballerina-io"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.0.4"

[[platform.java11.dependency]]
path = "../native/build/libs/io-native-1.2.2.jar"
version = "1.2.2"


[[platform.java11.dependency]]
path = "../test-utils/build/libs/io-test-utils-1.2.2.jar"
scope = "testOnly"
version = "1.2.2"
