[package]
org = "ballerina"
name = "io"
version = "1.6.2"
authors = ["Ballerina"]
keywords = ["io", "json", "xml", "csv", "file"]
repository = "https://github.com/ballerina-platform/module-ballerina-io"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.11.0"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "io-native"
path = "../native/build/libs/io-native-1.6.2-SNAPSHOT.jar"
version = "1.6.2"


[[platform.java17.dependency]]
path = "../test-utils/build/libs/io-test-utils-1.6.2-SNAPSHOT.jar"
scope = "testOnly"
version = "1.6.2-SNAPSHOT"
