[package]
org = "ballerina"
name = "io"
version = "1.6.1"
authors = ["Ballerina"]
keywords = ["io", "json", "xml", "csv", "file"]
repository = "https://github.com/ballerina-platform/module-ballerina-io"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.8.0"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "io-native"
path = "../native/build/libs/io-native-1.6.1.jar"
version = "1.6.1"


[[platform.java21.dependency]]
path = "../test-utils/build/libs/io-test-utils-1.6.1.jar"
scope = "testOnly"
version = "1.6.1"
