[package]
org = "ballerina"
name = "io"
version = "1.0.3"
distribution = "slbeta3"

[[platform.java11.dependency]]
path = "../native/build/libs/io-native-1.0.3-SNAPSHOT.jar"
version = "1.0.3-SNAPSHOT"


[[platform.java11.dependency]]
path = "../test-utils/build/libs/io-test-utils-1.0.3-SNAPSHOT.jar"
scope = "testOnly"
version = "1.0.3-SNAPSHOT"
